
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
include:
  - project: templates/ci
    file: DockerInDockerTemplate.yml

  
stages:
   - build
   - test
   - release
   - deploy

build-frontend-code-job:
  image: docker:20.10.12-dind-rootless
  services:
    - docker:dind
  stage: build
  before_script:
    - docker --version
    - until docker info; do sleep 2; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "$DOCKERHUB_TOKEN" | docker login --username $DOCKERHUB_LOGIN --password-stdin
  script:
    - cd frontend
    - docker build --build-arg VERSION=$VERSION --tag $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA . 
    - docker push $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA


upload-frontend-release:
  variables:
    GIT_STRATEGY: none
  image: docker:20.10.12-dind-rootless
  services:
    - docker:dind
  stage: release
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/sausage-frontend:latest
    - docker push $CI_REGISTRY_IMAGE/sausage-frontend:latest
  needs:
    - sonar-scanner
