---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |      
       server {
          listen       80;
          listen  [::]:80;
          error_log  /var/log/nginx/error_log;
          access_log /var/log/nginx/access_log;

            location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
              try_files $uri $uri/ /index.html;
            }

            location /api/ {
              proxy_pass http://backend:8081;
            }
         }